/* prettier-ignore-start */

/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file is auto-generated by TanStack Router

// Import Routes

import { Route as rootRoute } from './routes/__root'
import { Route as LoginImport } from './routes/login'
import { Route as DashboardImport } from './routes/dashboard'
import { Route as IndexImport } from './routes/index'
import { Route as DashboardMessagesImport } from './routes/dashboard.messages'
import { Route as DashboardExploreImport } from './routes/dashboard.explore'
import { Route as DashboardBillsImport } from './routes/dashboard.bills'
import { Route as DashboardListingIdImport } from './routes/dashboard.listing.$id'

// Create/Update Routes

const LoginRoute = LoginImport.update({
  path: '/login',
  getParentRoute: () => rootRoute,
} as any)

const DashboardRoute = DashboardImport.update({
  path: '/dashboard',
  getParentRoute: () => rootRoute,
} as any)

const IndexRoute = IndexImport.update({
  path: '/',
  getParentRoute: () => rootRoute,
} as any)

const DashboardMessagesRoute = DashboardMessagesImport.update({
  path: '/messages',
  getParentRoute: () => DashboardRoute,
} as any)

const DashboardExploreRoute = DashboardExploreImport.update({
  path: '/explore',
  getParentRoute: () => DashboardRoute,
} as any)

const DashboardBillsRoute = DashboardBillsImport.update({
  path: '/bills',
  getParentRoute: () => DashboardRoute,
} as any)

const DashboardListingIdRoute = DashboardListingIdImport.update({
  path: '/listing/$id',
  getParentRoute: () => DashboardRoute,
} as any)

// Populate the FileRoutesByPath interface

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexImport
      parentRoute: typeof rootRoute
    }
    '/dashboard': {
      id: '/dashboard'
      path: '/dashboard'
      fullPath: '/dashboard'
      preLoaderRoute: typeof DashboardImport
      parentRoute: typeof rootRoute
    }
    '/login': {
      id: '/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LoginImport
      parentRoute: typeof rootRoute
    }
    '/dashboard/bills': {
      id: '/dashboard/bills'
      path: '/bills'
      fullPath: '/dashboard/bills'
      preLoaderRoute: typeof DashboardBillsImport
      parentRoute: typeof DashboardImport
    }
    '/dashboard/explore': {
      id: '/dashboard/explore'
      path: '/explore'
      fullPath: '/dashboard/explore'
      preLoaderRoute: typeof DashboardExploreImport
      parentRoute: typeof DashboardImport
    }
    '/dashboard/messages': {
      id: '/dashboard/messages'
      path: '/messages'
      fullPath: '/dashboard/messages'
      preLoaderRoute: typeof DashboardMessagesImport
      parentRoute: typeof DashboardImport
    }
    '/dashboard/listing/$id': {
      id: '/dashboard/listing/$id'
      path: '/listing/$id'
      fullPath: '/dashboard/listing/$id'
      preLoaderRoute: typeof DashboardListingIdImport
      parentRoute: typeof DashboardImport
    }
  }
}

// Create and export the route tree

export const routeTree = rootRoute.addChildren({
  IndexRoute,
  DashboardRoute: DashboardRoute.addChildren({
    DashboardBillsRoute,
    DashboardExploreRoute,
    DashboardMessagesRoute,
    DashboardListingIdRoute,
  }),
  LoginRoute,
})

/* prettier-ignore-end */
